name: Static analysis

on:
  push:
    branches: [ "main","master","staging/0805" ]
  pull_request:
    branches:
      - "staging/**"
      - "master"
      - "main"

env:
  php-version: '8.0'

concurrency:
  group: Static analysis ${{ github.ref }}
  cancel-in-progress: true

jobs:
  codesniffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version
      - uses: reviewdog/action-setup@v1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Analyse all changed files
        run: |
          export REVIEWDOG_GITHUB_API_TOKEN="${{ secrets.github_token }}"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file start check..."
            filename=$(basename -- "$file")
            extension="${filename##*.}"
            if [ $extension == 'php' ]; then
              php phpcs.phar $file --standard=phpcs.xml --extensions=php
            else
              echo "$file isn't php file , skip..."
            fi
          done