name: "Unit Tests"

on:
  push:
    branches: [ master,main ]
  pull_request:
    branches:
      - "staging/**"
      - "master"
      - "main"
      
  workflow_run:
    workflows: ['Static analysis']
    types: [completed]      
jobs:
  tests:
  
    name: "Zipto Unit Test"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        
      - name: Checkout sources
        run: |
            echo "success"